### ISSUE TITLE
我才centos7 python3测试，无效

### ISSUE THREAD

**Issue by ghost** [Coldwave96/TcpRst#1]

**Comment by ghost** [comment]
我在centos7 python3下面，执行无效呢，是我环境问题吗？

**Comment by Coldwave96** [comment]
需要网卡开启混杂模式才能实现旁路阻断，不开混杂模式网卡会默认丢弃非本机的包。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"serven"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月23日(星期一) 下午4:22
收件人:&nbsp;"Coldwave96/TcpRst"<TcpRst@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Coldwave96/TcpRst] 我才centos7 python3测试，无效 (#1)




我在centos7 python3下面，执行无效呢，是我环境问题吗？

**Comment by ghost** [comment]
一样的，显示 Attacking 218.17.x.x and 183.x.x.x.实际还是成功的。

**Comment by ghost** [comment]
有微信或者qq么，方便在线沟通下么？

**Comment by Coldwave96** [comment]
qq吧，676803965



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: serven <notifications@github.com&gt;
发送时间: 2019年12月23日 18:20
收件人: Coldwave96/TcpRst <TcpRst@noreply.github.com&gt;
抄送: ColdWave <676803965@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Coldwave96/TcpRst] 我才centos7 python3测试，无效 (#1)




有微信或者qq么，方便在线沟通下么？
